version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

    groups:
      # Group 1: minor and patch updates
      safe-updates:
        patterns:
          - "*" # applies to all dependencies
        update-types:
          - "minor"
          - "patch"

      # Group 2: risky (major) updates
      breaking-updates:
        patterns:
          - "*"
        update-types:
          - "major"
