name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Lint
        run: npm run lint

      - name: Run tests (only if script exists)
        run: |
          if npm run | grep -q "test"; then
            echo "✅ Test script found. Running tests..."
            npm test
          else
            echo "⚠️ No test script found. Skipping tests."
          fi
